/*
A KBase module: kb_tophat2
*/

module kb_tophat2 {
    /* A boolean - 0 for false, 1 for true.
        @range (0, 1)
    */
    typedef int boolean;

    /* An X/Y/Z style reference
    */
    typedef string obj_ref;

    /*  
        required params:
        reads_ref: input reads object (Single/Paired_reads, reads_set, sample_set)
        bowtie_index: indexed genome object ref built using Bowtie2
        workspace_name: the name of the workspace it gets saved to
        alignment_object_name: output Alignment or AlignmentSet object name

        optional params:
        num_threads: number of processing threads
        read_mismatches: read mismatch cutoff
        read_gap_length: read gap cutoff
        read_edit_dist: read edit cutoff
        min_intron_length: minimum intron length
        max_intron_length: maximum intron length
        min_anchor_length: minimum anchor length
        report_secondary_alignments: use this option to output secondary alignments
        no_coverage_search: use this option to disable the coverage-based search for junctions
        library_type: library type (fr-unstranded, fr-firststrand, fr-secondstrand)
        preset_options: alignment preset options (b2-very-fast, b2-fast, b2-sensitive, b2-very-sensitive)

        ref: https://ccb.jhu.edu/software/tophat/manual.shtml
    */
    typedef structure {
        obj_ref reads_ref;
        obj_ref bowtie_index;
        string workspace_name;
        string alignment_object_name;

        int num_threads;
        int read_mismatches;
        int read_gap_length;
        int read_edit_dist;
        int min_intron_length;
        int max_intron_length;
        int min_anchor_length;
        boolean report_secondary_alignments;
        boolean no_coverage_search;
        string library_type; 
        string preset_options; 
    } TopHatInput;

    /*
        result_directory: folder path that holds all files generated by run_tophat2_app
        reads_alignment_object_ref: generated Alignment/AlignmentSet object reference
        report_name: report name generated by KBaseReport
        report_ref: report reference generated by KBaseReport
    */
    typedef structure{
        string result_directory;
        obj_ref reads_alignment_object_ref;
        string report_name;
        string report_ref;
    }TopHatResult;

    /*  
        run_tophat2_app: run TopHat2 app

        ref: https://ccb.jhu.edu/software/tophat/manual.shtml
    */
    funcdef run_tophat2_app(TopHatInput params)
        returns (TopHatResult returnVal) authentication required;
};
