
package us.kbase.kbtophat2;

import java.util.HashMap;
import java.util.Map;
import javax.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * <p>Original spec-file type: TopHatResult</p>
 * <pre>
 * result_directory: folder path that holds all files generated by run_tophat2_app
 * reads_alignment_object_ref: generated Alignment/AlignmentSet object reference
 * report_name: report name generated by KBaseReport
 * report_ref: report reference generated by KBaseReport
 * </pre>
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@Generated("com.googlecode.jsonschema2pojo")
@JsonPropertyOrder({
    "result_directory",
    "reads_alignment_object_ref",
    "report_name",
    "report_ref"
})
public class TopHatResult {

    @JsonProperty("result_directory")
    private String resultDirectory;
    @JsonProperty("reads_alignment_object_ref")
    private String readsAlignmentObjectRef;
    @JsonProperty("report_name")
    private String reportName;
    @JsonProperty("report_ref")
    private String reportRef;
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    @JsonProperty("result_directory")
    public String getResultDirectory() {
        return resultDirectory;
    }

    @JsonProperty("result_directory")
    public void setResultDirectory(String resultDirectory) {
        this.resultDirectory = resultDirectory;
    }

    public TopHatResult withResultDirectory(String resultDirectory) {
        this.resultDirectory = resultDirectory;
        return this;
    }

    @JsonProperty("reads_alignment_object_ref")
    public String getReadsAlignmentObjectRef() {
        return readsAlignmentObjectRef;
    }

    @JsonProperty("reads_alignment_object_ref")
    public void setReadsAlignmentObjectRef(String readsAlignmentObjectRef) {
        this.readsAlignmentObjectRef = readsAlignmentObjectRef;
    }

    public TopHatResult withReadsAlignmentObjectRef(String readsAlignmentObjectRef) {
        this.readsAlignmentObjectRef = readsAlignmentObjectRef;
        return this;
    }

    @JsonProperty("report_name")
    public String getReportName() {
        return reportName;
    }

    @JsonProperty("report_name")
    public void setReportName(String reportName) {
        this.reportName = reportName;
    }

    public TopHatResult withReportName(String reportName) {
        this.reportName = reportName;
        return this;
    }

    @JsonProperty("report_ref")
    public String getReportRef() {
        return reportRef;
    }

    @JsonProperty("report_ref")
    public void setReportRef(String reportRef) {
        this.reportRef = reportRef;
    }

    public TopHatResult withReportRef(String reportRef) {
        this.reportRef = reportRef;
        return this;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperties(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        return ((((((((((("TopHatResult"+" [resultDirectory=")+ resultDirectory)+", readsAlignmentObjectRef=")+ readsAlignmentObjectRef)+", reportName=")+ reportName)+", reportRef=")+ reportRef)+", additionalProperties=")+ additionalProperties)+"]");
    }

}
